version: '3.7'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: es1
    environment:
      - discovery.type=single-node
      #- node.name=es1
      #- cluster.name=es-docker-cluster
      #- cluster.initial_master_nodes=es1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    ports:
      - 9200:9200
    volumes:
      - data1:/usr/share/elasticsearch/data
    networks:
      - elastic
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - es1
    networks:
      - elastic
    #command: sh -c "python3 app/app.py"
    ports:
      - 8000:8000
    working_dir: /app
    restart: always

volumes:
  data1:
#    driver: local

networks:
  elastic:
#    driver: bridge

